### ISSUE TITLE
Null Check operator on Null value error

### ISSUE THREAD

**Issue by prajwal27** [fayeed/flutter_parsed_text#39]
![image](https://user-images.githubusercontent.com/31249460/123507393-af4db800-d686-11eb-894f-ced38cfe4f75.png)

`onTap` function is marked as nullable, but `!` null check operator is used on it, which results in an error in one of my apps.

If this is a legit issue, can I make an MR fixing this?

**Comment by Brinfotech1407** [comment]
I am to facing this issue

Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      ParsedText.build.<anonymous closure>.<anonymous closure> (package:flutter_parsed_text/src/parsed_text.dart:170:46)
#1      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#2      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
#3      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#4      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
...

**Comment by JhonyPerez** [comment]
Fix for the issue: https://github.com/fayeed/flutter_parsed_text/pull/50
